### ISSUE TITLE
Unicity is not checked. There is a test that check...

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/RETIRED-cross-cutting-issues#1]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

Unicity is not checked. There is a test that checks whether an element is available and not empty. But there is no control whether this element occurs just once or multiple times.

**Comment by cportele** [comment]
This does not seem to be a cross-cutting issue, but a comment on a specific test case.

Proposed resolution:
- Clarify comment and proposal, including which test case needs to be improved. Otherwise close the issue.
