### ISSUE TITLE
The documentation of the test cases is inconsisten...

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/RETIRED-cross-cutting-issues#10]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

The documentation of the test cases is inconsistent. Sometimes the title is the label (A.xxx.xxx) and sometimes a text.
# Proposed Change

Make the test case documentation consistent.

**Comment by michellutz** [comment]
Agreed in principle.

@EmidioStani, @cportele Please make a concrete proposal for the naming convention to be used.

**Comment by cportele** [comment]
Proposed Resolution:
- Use an identifier as the title.
- Use a mnemonic identifier that gives an idea of what the test case is about. 
- Use the purpose section to describe for humans what the test case is about.

**Comment by cportele** [comment]
Proposed resolution accepted by default. See [call on April 28](https://ies-svn.jrc.ec.europa.eu/projects/validation-and-conformity-testing/wiki/MIWP-5_meeting_10#Next-steps).

**Comment by cportele** [comment]
Here is an overview of the name changes.

[ATS - Name changes.xlsx](https://github.com/inspire-eu-validation/ats-cross-cutting/files/391072/ATS.-.Name.changes.xlsx)
