### ISSUE TITLE
Unfortunately we had not had enough time to go thr...

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/RETIRED-cross-cutting-issues#13]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

Unfortunately we had not had enough time to go through all documents, but we have found parts of the document that are too general. They should be more specific if the purpose is to be able to validate Inspire conformance.
The following example is taken from ATS metadata.
- A04 is an example of too general text;
  Test method
  Checks if a resource type (hierarchyLevel) is provided and is taken from the MD_ScopeCode codelist.
  To be relevant for INSPIRE the value should be either 'dataset', 'service' or 'series'
  This test is relevant for Inspire, so the value should just consist of 'dataset', 'service' or 'series'
- A24 is an example of when the test is written more precise (good example);
  Test method
  The test first checks if there is at least one role element. The element must contain an element at gmd:CI_RoleCode[@codeListValue=x], where x is one of the values described in ISO 19115, chapter B.5.5.
  # Proposed Change
  When Inspire is precise in its requirements, e.g. resource type, then the test should also be more precise.

**Comment by cportele** [comment]
Generally agreed, but this needs to be addressed on a test case by test case basis.

Regarding A04, I agree.

Proposed resolution:
- This issue should be addressed by the existing specific comments on test cases.
- In A04 change test method to allow only the three values and identify the URIs that have to be used. As the referenced code list only has the three values, this is an editorial change.

**Comment by cportele** [comment]
Proposed resolution accepted by default. See [call on April 28](https://ies-svn.jrc.ec.europa.eu/projects/validation-and-conformity-testing/wiki/MIWP-5_meeting_10#Next-steps).
