### ISSUE TITLE
The target of tests are not clear enough. It is hi...

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/RETIRED-cross-cutting-issues#14]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

The target of tests are not clear enough. It is hidden in the method sometimes or in the prerequistes  in others.
# Proposed Change

Add a target field.

**Comment by cportele** [comment]
Agreed. The standardization target of all test cases in a conformance class has to be the same. And it should be clearly stated for all conformance classes.

If the comment is about more clearly identifying the aspect of the standardization target that is tested by a test case, then I agree it is important to make it clear. However, in some cases a single test case, for example, tests aspects of a capabilities document and of several service responses where the request have been constructed based on the content of the capabilities document. If these aspects can unambiguously understood from the test method, this seems sufficient to me.

**Comment by cportele** [comment]
Proposed resolution:
- Identify standardization target in every conformance class (now often called "ATS").

**Comment by cportele** [comment]
Proposed resolution accepted by default. See [call on April 28](https://ies-svn.jrc.ec.europa.eu/projects/validation-and-conformity-testing/wiki/MIWP-5_meeting_10#Next-steps).
