### ISSUE TITLE
QoS for View and Discovery Services

### ISSUE THREAD

**Issue by cportele** [inspire-eu-validation/RETIRED-cross-cutting-issues#15]
The Technical Guidelines for the View and Discovery Services do not identify the requirements as such or assign an identifier. They also do not identify conformance classes. It is unclear how the handle this issue in the ATS for these Technical Guidelines.

**Comment by michellutz** [comment]
@cportele I am not quite sure I understand the comment that "the Technical Guidelines for the View and Discovery Services do not identify the requirements as such or assign an identifier". There are clearly marked and numbered "Implementation requirements" in these TGs.

For the missing conformance classes, I would suggest the following:
- Discovery
  - CSW ISO AP
  - Quality of service
- View
  - ISO 19128 (WMS 1.3.0)
  - WMTS 1.0.0
  - WMS 1.1.1 (??)
  - Quality of service

**Comment by cportele** [comment]
@michellutz I searched for "requirement" and only looked at those. In the PDFs I have the requirements are indeed there (based on the style), but without the number and the "requirement" label. That should be fixed in an update.

Regarding a segmentation into conformance classes: 
- I do not see a conformance class for WMS 1.1 (or WMS-C). There is no specification that could be used for testing, just examples how the extended capabilities might be defined.
- Regarding the View Service QoS conformance class, it really is a WMS 1.3 View Service QoS conformance class and does not cover WMTS. It contains requirements like: "For a Get Map request, the reference request shall request images of 800x600 pixels with a colour depth of 8 bits according to the image formats mandated by the regulation". Or references to BBOX parameters. In general it will be difficult to specify testable requirements independent of the implementation, i.e. I think there needs to be a conformance class per implementation  option. Or maybe there is a single one, if the options are close enough, but the requirements will need to differentiate between the implementation options.

**Comment by cportele** [comment]
If the proposal in https://github.com/inspire-eu-validation/ats-view-wmts/issues/34 is followed, there needs to be another conformance class for the metadata/extended capabilties.

**Comment by michellutz** [comment]
Agreed.

**Comment by michellutz** [comment]
Agreed resolution:

The structure of the conformance classes should be:

Discovery
- CSW ISO AP
- Metadata/extended capabilties
- Quality of service

View
- ISO 19128 (WMS 1.3.0)
- WMTS 1.0.0
- Metadata/extended capabilties
- Quality of service WMS
- Quality of service WMTS (if requirements are available in the TG)
