### ISSUE TITLE
Timeout on requests to Network Services and sleep-mode.

### ISSUE THREAD

**Issue by aquaglia** [inspire-eu-validation/RETIRED-cross-cutting-issues#17]
An agreed-upon  timeout on requests to Network Services is needed both in the ATSs and in the ETSs.
The sleep-mode present in several implementations is also an important factor to take into account.

**Comment by cportele** [comment]
Resolution during [call on April 28](https://ies-svn.jrc.ec.europa.eu/projects/validation-and-conformity-testing/wiki/MIWP-5_meeting_10):
- Agreement on consistent timeouts across CCs. Needs to be on a request level as they are different. Some are specified in IR/TG, but not all, e.g. when accessing other remote resources like code list values. Use 30s, if there is nothing stated in the technical guidance.
- Impact of sleep-mode should be "taken into account" in the TG first, if it needs to be taken into account in the tests  -> flag as TGCR issue.

**Comment by cportele** [comment]
See #18.
