### ISSUE TITLE
How is multilinguism taken into account?...

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/RETIRED-cross-cutting-issues#2]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

How is multilinguism taken into account?

**Comment by cportele** [comment]
Currently there is no support. The Technical Guidelines are also available only in English and the ATS are logically a part of the Technical Guidelines.

**Comment by cportele** [comment]
Note: No changes required
