### ISSUE TITLE
It seems these tests can't be run in an automated ...

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/RETIRED-cross-cutting-issues#3]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

It seems these tests can't be run in an automated way against the software. 
It's possible to do this with OGC web services using CITE tests. Some third parties do this for CSW at the moment. 
Do you know of any pending plans to implement the test suite for automated testing.

**Comment by cportele** [comment]
ATS are by definition abstract. Test cases with type "automated" should be implementable in automated testing and there is an ARE3NA project to support this.

**Comment by cportele** [comment]
Note: No changes required
