### ISSUE TITLE
Grouplayers will not be validated under the curren...

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/RETIRED-cross-cutting-issues#4]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

Grouplayers will not be validated under the current proposal. However, their use is being promoted within the Geology theme to satisfy the present guidelines.

**Comment by cportele** [comment]
Agreed in principle.

Proposed resolution:
- MIG-T to amend the View Service Technical Guidelines with the rules for using group layers.
- Clarify how to change to test cases to support group layers.

**Comment by cportele** [comment]
As mentioned by @aquaglia in the call: This only applies to group layers with a name.

**Comment by cportele** [comment]
Resolution agreed in call on April 15:
- Add a note in the test case that group layers with a name will fail the test.
- MIG-T to amend the View Service Technical Guidelines with the rules for using group layers.
- Clarify how to change test cases to support group layers after amendment is available.
