### ISSUE TITLE
Based on ISO 19105 and the OGC Specification Model...

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/RETIRED-cross-cutting-issues#5]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

Based on ISO 19105 and the OGC Specification Model, each Markdown document represents a test case. A test case is part of a conformance class, which in turn is part of an abstract test suite for a specification document.
The current material seems to use 'ATS' where 'Conformance Class' is probably meant. The information which conformance classes form an ATS is, however, not represented. 
In this context it is important to emphasize that conformance class is the key concept. An ATS is far less important as it is just the aggregation of all the conformance classes in a specification.
In addition, the term 'ATS' is sometimes also used for a test case.
# Proposed Change

Use 'Conformance Class' (or 'CC'/'cc') where 'Abstract Test Suite' (or 'ATS'/'ats') is used now - and where the Technical Guidance includes (implicitly or explicitly) a conformance class. Avoid using wrong a misleading term for test cases.
Group the conformance classes into ATSs based on the specifications that define the conformance classes.
I.e., the structure would be for the current 'ATS's:
ATS: TG View Service 3.11
CC: WMS 1.3.0 profile
TC: A.02.IR04.extended...
TC: A.03.IR05.schema...
TC: ... (no more test cases shown below)
CC: WMTS 1.0.0 profile
ATS: TG Discovery Service 3.1
CC: CSW 2.0.2 ISO AP profile
 ATS: TG Download Service 3.1
CC: Pre-defined Atom
CC: Pre-defined WFS 2.0.0
CC: Direct WFS 2.0.0
CC: Quality of Service
ATS: TG Metadata 1.3
CC: ISO 19115/19119 profile
ATS: TG Spatial Data Services 3.1
CC: Invocable Spatial Data Services 
CC: Interoperable Spatial Data Services
CC: Harmonized Spatial Data Services 
Notes:
TG View Services: The document does not explicitly specify conformance classes for the two OGC standards, but implicitly these are defined as 'profiles'. 
TG View and Discovery Services: It is unclear how the requirements regarding QoS have to be treated as the requirements are not identified as requirements with an identifier.

**Comment by michellutz** [comment]
Agreed.

@EmidioStani, @cportele: This open issue should probably be dealt with as a separate issue:
TG View and Discovery Services: It is unclear how the requirements regarding QoS have to be treated as the requirements are not identified as requirements with an identifier.

**Comment by cportele** [comment]
@michellutz I have created a new issue for the QoS aspect. See #15.
