### ISSUE TITLE
An ATS belongs to a specification. Therefore, the ...

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/RETIRED-cross-cutting-issues#6]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

An ATS belongs to a specification. Therefore, the references in a test case may only reference one specification. 
However, currently sometimes an IR and a TG are referenced. This is not consistent with the notion of conformance classes or abstract test suites. Since IRs do not specify conformance classes and this is typically done in a technical guidance document, the reference should go to the TG (and the requirement in the TG should reference the relevant parts of the IR).
# Proposed Change

For each test case, identify/reference the relevant requirements in the TG document that specifies the conformance class. 

For TGs that identify requirements, list the requirements, otherwise list the most specific section.

**Comment by michellutz** [comment]
Agreed. Test cases should only refer to TG requirements, not parts of the IR.
