### ISSUE TITLE
For cases where a dependency exists to an external...

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/RETIRED-cross-cutting-issues#7]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

For cases where a dependency exists to an external conformance class (dependencies are always on the conformance class level, not on the level of test suites or test cases), clearly identify the conformance class.
# Proposed Change

See comment. For example, do not reference tests 'OGC FES 2.0, A.1 Test cases for query', but reference OGC FES 2.0 Conformance Class 'Query'.

**Comment by michellutz** [comment]
Agreed.

**Comment by ilkkarinne** [comment]
Agreed. I think quick check of the used OGC specification references would be good to make sure the INSPIRE tests really should be inclusive of all the test in the referred external CCs.
