### ISSUE TITLE
The section 'Prerequisites' should have a reliable...

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/RETIRED-cross-cutting-issues#9]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

The section 'Prerequisites' should have a reliable structure. Prerequisites should only be other test cases in the same conformance class or other conformance classes.
In some cases, this section does not state other tests that need to be passed first, but actually state new tests.
# Proposed Change

Update 'Prerequisites' to be a list of other test cases in the same conformance class or other conformance classes.
Any prerequisites that actually are new tests need to be converted into separate test cases or included in the test method description.

**Comment by michellutz** [comment]
The proposed change was discussed an agreed in the [MIWP-5 meeting on 16 April](https://ies-svn.jrc.ec.europa.eu/projects/validation-and-conformity-testing/wiki/MIWP-5_meeting_8#Consistency).

In addition, it was proposed that a distinction be made between dependencies and conditional tests; the latter should be either expressed through a separate condition specifying when the test has to be executed (e.g. "when there is more than one language") or (if there are not so many cases of conditional tests) as part of the test description.

**Comment by cportele** [comment]
I do not think a concept like "conditional test" is needed. A requirement is a requirement. If a requirement is applicable only in certain situations and this is part of the requirement, the conditions should be described as part of the test method. Sometimes the conditions can only be checked in test steps during the execution of a test case.

If a condition is important enough it should be used as a basis for a new conformance class (in the Technical Guidance).

**Comment by michellutz** [comment]
I agree with Clemens' comment.

**Comment by ilkkarinne** [comment]
+1 @cportele
